# Generated by Django 5.0.7 on 2024-10-08 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_payment_orderplaced'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stock_status',
            field=models.CharField(choices=[('IN', 'In Stock'), ('LT', 'Limited Stock'), ('OUT', 'Out of Stock')], default='IN', max_length=3),
        ),
    ]
